### ISSUE TITLE
support disregarding vulnerabilities that don't have fix yet

### ISSUE THREAD

**Issue by sambercovici** [naugtur/audit-resolver-core#6]
In CI, it would be helpful to be able to run check-audit in a way that will not fail when detecting issues that don't have a fix yet.

**for example:**
check-audit --json
**reports:**
[
  {
    "id": 1091410,
    "name": "request",
    "title": "Server-Side Request Forgery in Request",
    "url": "https://github.com/advisories/GHSA-p8p7-x288-28g6",
    "severity": "moderate",
    "range": "<=2.88.2",
    _**"fixAvailable": false,**_
    "paths": [
      "@kubernetes/client-node>request"
    ],
    "resolutions": [
      {
        "path": "@kubernetes/client-node>request",
        "resolution": "none"
      }
    ]
  }
]

**Comment by naugtur** [comment]
It would be a disaster for a project's security if that happened automatically. 
This tool is here to let you decide to explicitly ignore an issue once you're aware it's there. 

Feel free to reopen if you think I misunderstood.

**Comment by sambercovici** [comment]
If there is NO fix and failing the CI, then I need to ignore for a period which is worse then failing the CI immediately when a fix becomes available.
In other words, scanners out there have options to turn off reporting CVEs that do not have a fix. This is of course not enabled by default. Alternatively, its also ok, to add this to audit-resolve.json and a decision type "ingnoreUnfixed" 
something like:  
{
  "decisions": {
    "1091410|@kubernetes/client-node>request": {
      "decision": **"ingnoreUnfixed"**,
      "madeAt": 1679305978080
    }
  },
  "rules": {},
  "version": 1
}
